### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device (RTX 5060 Ti, torch rand on cuda:0)

### ISSUE THREAD

**Issue by Zhenyu2Liang** [EMI-Group/evogo#1]
### Description
When running the provided example script, the program crashes immediately during `HarderNumerical` initialization.  
The failure happens at the first CUDA tensor creation (`torch.rand(..., device="cuda:0")`) with:
RuntimeError: CUDA error: no kernel image is available for execution on the device

My GPU is **RTX 5060 Ti**, and the environment was installed using the repo script:

```bash
bash setup_env_torch.sh
```

This error typically indicates the installed PyTorch/CUDA build does not contain kernel images for the GPU architecture (CUDA arch mismatch).

### Steps to Reproduce

1.Install the environment using the repo script:

```bash
bash setup_env_torch.sh
```

Run the following example:

```python
import torch
import numpy as np

from evogo_torch.evogo import EvoGO
from test_functions.simple_functions import HarderNumerical

if __name__ == "__main__":
    # Configuration
    dim = 5
    num_parallel = 2
    seed = 42
    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    device_obj = torch.device(device)

    print(f"Running on {device}")

    # Initialize the problem
    problem = HarderNumerical(
        dim=dim,
        device=device_obj,
        eval_fn=HarderNumerical.Rosenbrock,
        instances=num_parallel
    )

    # Initialize the algorithm
    solver = EvoGO(
        max_iter=5,
        batch_size=100,
        gm_batch_size=100,
        num_parallel=num_parallel,
        use_gp=True,
        debug=True,
        gpu_id=0 if "cuda" in device else -1
    )

    # Call the solve method
    print(f"Starting to solve {dim}-dimensional Rosenbrock function (HarderNumerical)...")

    best_x, best_y = solver.solve(problem, dim=dim, seed=seed, device=device)

    print("\n" + "=" * 30)
    print(f"Optimization Complete!")
    print(f"Best x (normalized input to solver): {best_x}")
    print(f"Best y: {best_y}")
    print("=" * 30)
```

### Actual Behavior

Output:
```
Running on cuda:0
Traceback (most recent call last):
  File "/mnt/c/Users/lemon/Desktop/test/evogo/test1.py", line 18, in <module>
    problem = HarderNumerical(
              ^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/lemon/Desktop/test/evogo/test_functions/simple_functions.py", line 29, in __init__
    self.re_init(device)
  File "/mnt/c/Users/lemon/Desktop/test/evogo/test_functions/simple_functions.py", line 35, in re_init
    torch.rand(self.instances, self.dim, device=device) * self.range + self.lb / self.scaling
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Expected Behavior

The example should run successfully on GPU, or at least not fail at a basic CUDA op like ```torch.rand(...)```.

### Environment

GPU: NVIDIA RTX 5060 Ti

OS: Windows + WSL2 (Ubuntu)

Installed via: bash setup_env_torch.sh

Please let me know if you need full outputs. I can provide:

```
python -c "import torch; print('torch:', torch.__version__); print('cuda:', torch.version.cuda); print('available:', torch.cuda.is_available()); print('device:', torch.cuda.get_device_name(0)); print('capability:', torch.cuda.get_device_capability(0))"
nvidia-smi
nvcc --version
```

Thanks!

**Comment by JiangTao97** [comment]
Thanks for the detailed report! This error (**“no kernel image is available”**) usually means the installed PyTorch/CUDA build doesn’t include kernel support for your GPU architecture (arch mismatch). Since you’re on an **RTX 5060 Ti (50-series)**, it’s quite possible the repo script installed a **CUDA 12.4 / PyTorch** wheel that doesn’t fully support 50-series yet.

Could you try upgrading to a newer CUDA/PyTorch build (e.g. **CUDA 12.8**) and reinstalling PyTorch against that runtime? That should pull a wheel with proper kernel images for your GPU.

**Comment by Zhenyu2Liang** [comment]
Thanks for the suggestion — after upgrading to CUDA 12.8 + PyTorch cu128, the issue is fully resolved on my RTX 5060 Ti.

For completeness, here is my full `pip list` from the working environment:


<details>
<summary>Full environment (pip list)</summary>

```text
Package                   Version
------------------------- ------------
alembic                   1.17.0
attrs                     25.4.0
certifi                   2025.10.5
charset-normalizer        3.4.4
click                     8.2.1
colorlog                  6.10.1
evox                      1.2.2
filelock                  3.19.1
fsspec                    2025.9.0
greenlet                  3.2.4
idna                      3.11
Jinja2                    3.1.6
jsonschema                4.25.1
jsonschema-specifications 2025.9.1
Mako                      1.3.10
MarkupSafe                2.1.5
mpmath                    1.3.0
msgpack                   1.1.2
networkx                  3.3
numpy                     2.1.2
nvidia-cublas-cu12        12.8.4.1
nvidia-cuda-cupti-cu12    12.8.90
nvidia-cuda-nvrtc-cu12    12.8.93
nvidia-cuda-runtime-cu12  12.8.90
nvidia-cudnn-cu12         9.10.2.21
nvidia-cufft-cu12         11.3.3.83
nvidia-cufile-cu12        1.13.1.3
nvidia-curand-cu12        10.3.9.90
nvidia-cusolver-cu12      11.7.3.90
nvidia-cusparse-cu12      12.5.8.93
nvidia-cusparselt-cu12    0.7.1
nvidia-nccl-cu12          2.27.5
nvidia-nvjitlink-cu12     12.8.93
nvidia-nvshmem-cu12       3.3.20
nvidia-nvtx-cu12          12.8.90
optuna                    4.5.0
packaging                 25.0
pandas                    2.3.3
pillow                    11.3.0
pip                       25.2
protobuf                  6.33.0
pyarrow                   22.0.0
pygame                    2.6.1
python-dateutil           2.9.0.post0
pytz                      2025.2
PyYAML                    6.0.3
ray                       2.50.1
referencing               0.37.0
requests                  2.32.5
rpds-py                   0.28.0
scipy                     1.15.3
setuptools                80.9.0
six                       1.17.0
SQLAlchemy                2.0.44
sympy                     1.14.0
tensorboardX              2.6.4
tomli                     2.3.0
torch                     2.9.0+cu128
torchvision               0.24.0+cu128
tqdm                      4.67.1
triton                    3.5.0
typing_extensions         4.15.0
tzdata                    2025.2
urllib3                   2.5.0
wheel                     0.45.1
